# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourcesFromaBroad',
        ),
    ]
