# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20171105_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesfromabroad',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品种名称'),
        ),
    ]
